### ISSUE TITLE
Add instructions on git submodule management

### ISSUE THREAD

**Issue by tmsdkeys** [polymerdevs/community-demo-dapps#9]
After syncing with @kenobijon we decided to require projects to be added as git submodule to make the repo size manageable, while still allowing the initial goal of providing visibility and access for our Polymer devs to some of the most exciting community projects.

Git submodules is not an everyday concept for all devs and might require some guidances on the readme...

Let's add best practices / recommendations to use the repo (not only when adding a project)

**Comment by kenobijon** [comment]
added git-submodules.md for best practices
